name: Import new Rock
on:
  workflow_dispatch:
    inputs:
      rock_name:
        description: The name of the library to be imported
        required: true
      rock_version:
        description: The version of the library
        required: true
      description:
        description: Where is this required? Write some context (with links if possible)
        required: true

run-name: Add rock ${{ inputs.rock_name }} ${{ inputs.rock_version }}

jobs:
  add_rock:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Add the Rock
        run: ./add-rock.sh ${{ inputs.rock_name }} ${{ inputs.rock_version }}

      - name: Set up Git credentials
        run: |
          git config user.name "team-gateway-bot"
          git config user.email "team-gateway-bot@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.KONG_PR_PAT }}@github.com/Kong/kongrocks-dev.git

      - name: Open PR
        uses: Kong/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7
        with:
          token: ${{ secrets.KONG_PR_PAT }}
          author: team-gateway-bot <team-gateway+github-bot@konghq.com>
          committer: team-gateway-bot <team-gateway+github-bot@konghq.com>
          base: main
          branch: add-${{ inputs.rock_name }}-${{ inputs.rock_version }}
          add-paths: |
            rocks/*
          title: add ${{ inputs.rock_name }} ${{ inputs.rock_version }}
          body: |
            ### Summary
            Add new library **${{ inputs.rock_name }} ${{ inputs.rock_version }}**.
            ### Observations
            - This PR was generated with `./add-rocks.sh`
            - `luarocks-admin make_manifest` will at times change the ordering
            of table fields in `rock/manifest*` files; please ignore these!
            ### Author
            The workflow was dispatched by @${{ github.actor }}, with the following description:
            > ${{ inputs.description }}

          commit-message: |
            chore(deps): add ${{ inputs.rock_name }} ${{ inputs.rock_version }}

            workflow dispatched by @${{ github.actor }}, with the following details:
            > ${{ inputs.description }}
